### ISSUE TITLE
无法下单

### ISSUE THREAD

**Issue by airinair** [ValPromise/vpp-server#1]
操作步骤：
1.在任意币价行情界面点击涨（跌）按钮

预期结果：
1.涨（跌）按钮右下角显示黄色的勾

实际结果：
1.涨（跌）按钮右下角没有显示黄色的勾，且无任何提示，且数据库中也没有记录数据

**Comment by huahuayu** [comment]
是否必现？我能想到的一种情况是两个系统的时间差超过系统允许的范围（目前15秒）就会下不了单，并且没有任何提示（因为我们把报错信息：非法下单时间戳，隐藏了。

目前版本测试我没发现这个问题，请再看看  @airinair
