### ISSUE TITLE
偶尔出现下单后无法开奖的情况

### ISSUE THREAD

**Issue by airinair** [ValPromise/vpp-server#2]
操作步骤：
1.在任意币价行情界面点击涨（跌）按钮，完成下单
2.等待开奖

预期结果：
1.会弹出开奖结果

实际结果：
1.没有弹出开奖结果，且后面也无法开奖，订单状态一直是 等待判定

**Comment by huahuayu** [comment]
1. 5分钟没开奖（order_list_coin.status = 0-等待判定 状态的）自动退款，退款时会增加用户余额，减少庄家余额 
2. 因系统时间差（java后台系统时间40秒时收到来自安卓下单时间为29秒的订单）造成不能开奖的，现在能开奖了

请重测 @airinair

**Comment by ValPromise** [comment]
@airinair 生产上无新的开不了奖的订单出现，关闭issue
